---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: networking
    - name: cert-manager
      namespace: cert-manager      
  values:
    image:
      longhorn:
        engine:
          repository: longhornio/longhorn-engine
          tag: master-head
        manager:
          repository: longhornio/longhorn-manager
          tag: master-head
        ui:
          repository: longhornio/longhorn-ui
          tag: master-head
        instanceManager:
          repository: longhornio/longhorn-instance-manager
          tag: master-head
        shareManager:
          repository: longhornio/longhorn-share-manager
          tag: master-head
        backingImageManager:
          repository: longhornio/backing-image-manager
          tag: master-head
        supportBundleKit:
          repository: longhornio/support-bundle-kit
          # tag: v0.0.22
      csi:
        attacher:
          repository: longhornio/csi-attacher
          # tag: v3.4.0
        provisioner:
          repository: longhornio/csi-provisioner
          # tag: v2.1.2
        nodeDriverRegistrar:
          repository: longhornio/csi-node-driver-registrar
          # tag: v2.5.0
        resizer:
          repository: longhornio/csi-resizer
          # tag: v1.3.0
        snapshotter:
          repository: longhornio/csi-snapshotter
          # tag: v5.0.1
        livenessProbe:
          repository: longhornio/livenessprobe
          # tag: v2.8.0
        
      pullPolicy: IfNotPresent

    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain

    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1

    defaultSettings:
      backupTarget: nfs://${NAS_ADDRESS}:/volume2/plex_config/backups
      defaultReplicaCount: 1

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik 
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hajimari.io/appName: "Longhorn"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cow"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: longhorn-tls
