---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: networking
    - name: cert-manager
      namespace: cert-manager      
  values:
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      backupTarget: nfs://${NAS_ADDRESS}:/volume2/plex_config/backups
      defaultReplicaCount: 1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik 
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hajimari.io/appName: "Longhorn"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cow"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: longhorn-tls
