apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  dsm: '${NAS_ADDRESS}'
  location: '/volume12'
  fsType: 'btrfs'
reclaimPolicy: Retain
allowVolumeExpansion: true
