---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mealie
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: hkotel/mealie
    env: 
      TZ: "America/Denver"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik 
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/appName: "Mealie"
          hajimari.io/enable: "true"
          hajimari.io/icon: "chef-hat"
        hosts:
          - host: "mealie.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "mealie.${SECRET_DOMAIN}"
            secretName: "mealie-tls"
