apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-secrets
    namespace: home
stringData:
    adminPassword: ENC[AES256_GCM,data:jr6s34+S7K2/PJFJl11L7avLUuf0y1jKztj3j5by5MI=,iv:zHCP3KG+irix7/c0KXRplSHNiq2gHOGIvCHjdmlaYV0=,tag:vRz2eehgcqq9RTJ7tSGogQ==,type:str]
    userPassword: ENC[AES256_GCM,data:CzxqhXt7f8TdkY+N54PfroXx1DghjJph9WHAnQ43fgF2fDlKPw==,iv:2Z3Y5hq85RfBbtL2k3XC7auTEIUz5IZ1BVTwBZkuIEY=,tag:fQiqaKr6HBVnEyMTs8L3ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9nkequ7a7k26n0gvj0j6pm4my9wehxxw8adfwq36yyf267fsffs57shza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z09HRklWaHpmUUU3a1F0
            TUYyY2ozNjV1Z3RvS2RYNlJvekxSZ3I4MVZrCnhhSlJ1Q1VUQnFKa2NWV015VzZO
            WEw5RVlNT0ZWc24vcExDN1JHWE4weWsKLS0tIGdzWUR5Nm9OSThHWEpmVjdSNkFP
            QU43NSs4aWVkMzljTDhlbWhFQmZYSncKjAfHLr+aY0nnLUapQuglo/ZxRD97vlm4
            +IcBSU+3NRgHeMtVikFv+ApSXPp7xohLGtn32caTYs8oyzqK0ndudw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-24T05:38:39Z"
    mac: ENC[AES256_GCM,data:sp1qYYWDfatOKZNtEXRZCidu80oOxbx4ectjxB53yHMJzCLxZSrpNwFetGVIxMBuTFlTArDMkdGPUdC7camL9UljNWGDl/Yr9RFN36lnSSCCknKwyfbsmXgcKPKb6bx1fmGtyF5D/SMn5b16ZctTAKdbEPr95tNm7REMjttPSQ8=,iv:j4EHhJwNQU47CDlzEot2wwoQK95yub6Z/WEFZXmKsQU=,tag:Lha4y039TXs/aW7u2RQrYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
