---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: esphome
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: 2024.4.2
      pullPolicy: IfNotPresent
    replicaCount: 0
    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
    persistence:
      config:
        enabled: true
        existingClaim: "home-assistant-config-pvc"
        subPath: esphome
    service:
      main:
        type: NodePort
        ports:
          http:
            enabled: true
            nodePort: 31933
