---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: esphome
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: 2021.8.0
      pullPolicy: IfNotPresent
    replicaCount: 0
    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
    persistence:
      config:
        enabled: true
        existingClaim: "home-assistant-config-pvc"
        subPath: esphome
    ingress:
      main:
        enabled: true
        hosts:
          - host: esphome.${SECRET_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
