---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://releases.rancher.com/server-charts/stable
      chart: rancher
      version: 2.6.3
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  interval: 15m0s
  values:
    replicas: 1
    ingress:
      enabled: false
    #   tls:
    #     source: letsEncrypt
    # hostname: rancher.${SECRET_DOMAIN}
