---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
  interval: 15m0s
  values:
    ingress:
      enabled: false
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${METALLB_TRAEFIK_ADDR}"
        externalTrafficPolicy: Local