---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      chart: rancher
      version: 2.6.2
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  interval: 15m0s
  values:
    ingress:
      tls:
        source: letsEncrypt
    hostname: rancher.${SECRET_DOMAIN}