apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.17
    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 2
    env:
      TZ: "America/Denver"
    service:
      main:
        ports:
          http:
            port: 4000
      dns:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${SVC_BLOCKY_ADDR}"
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
    metrics:
      enabled: false
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
      prometheusRule:
        enabled: false
    config: |
      upstream:
        default:
          - ${LOCAL_UPSTREAM_DNS_1}
          - ${DEFAULT_GATEWAY}
      customDNS:
        mapping:
          ${SECRET_DOMAIN}: ${METALLB_TRAEFIK_ADDR}
          games.${SECRET_DOMAIN}: ${GAME_SERVER_IP}
      blocking:
        blackLists:
          ads:
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
            - |
              /^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]/
              /^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]/
              /^(.+[_.-])?telemetry[_.-]/
              /^adim(age|g)s?[0-9]*[_.-]/
              /^adtrack(er|ing)?[0-9]*[_.-]/
              /^advert(s|is(ing|ements?))?[0-9]*[_.-]/
              /^aff(iliat(es?|ion))?[_.-]/
              /^analytics?[_.-]/
              /^banners?[_.-]/
              /^beacons?[0-9]*[_.-]/
              /^count(ers?)?[0-9]*[_.-]/
              /^mads\./
              /^pixels?[-.]/
              /^stat(s|istics)?[0-9]*[_.-]/
        whiteLists:
          ads:
            - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: tcp+udp:${DEFAULT_GATEWAY}
      prometheus:
        enable: false
        path: /metrics
      bootstrapDns: tcp:1.1.1.1
      httpPort: 4000
      logFormat: json
      logLevel: warn
    persistence:
      whitelists:
        enabled: true
        mountPath: /app/whitelists
        type: custom
        volumeSpec:
          configMap:
            name: blocky-whitelist
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
