---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  labels:
    category: game
    app: factorio
  namespace: games
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec: 
      containers:
        - name: factorio
          image: factoriotools/factorio:1.1.100
          ports:
            - containerPort: 34197
          volumeMounts:
            - mountPath: /factorio
              name: factorio-vol
          env:
            - name: SAVE_NAME
              value: live
            - name: LOAD_LATEST_SAVE
              value: "false"
            - name: TOKEN
              value: ${SECRET_FACTORIO_TOKEN}
            - name: USERNAME
              value: ${SECRET_FACTORIO_USERNAME}
      volumes:
        - name: factorio-vol
          persistentVolumeClaim:
            claimName: factorio-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
