---
apiVersion: v1
kind: Service
metadata:
  name: factorio-port
  namespace: games
spec:
  type: LoadBalancer
  selector:
    app: factorio
  externalIPs:
    - "${GAME_SERVER_IP}"
  ports:
    - protocol: UDP
      port: 32000
      targetPort: 34197
