---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-pv
  namespace: games
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume4/factorio
    server: 192.168.1.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc-1
  namespace: games
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi