apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.32.0.6918-6f393eda1
      pullPolicy: IfNotPresent

    env:
      TZ: "America/Denver"
      # ALLOWED_NETWORKS: 192.168.1.0/255.255.255.0
      # PLEX_CLAIM: ${SECRET_PLEX_CLAIM}
      PLEX_PREFERENCE_1: "FriendlyName=HancockPlex"
      PLEX_PREFERENCE_4: "DisableTLSv1_0=1"

    hostNetwork: true

    dnsPolicy: ClusterFirstWithHostNet

    ingress:
      main:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: traefik 
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/appName: "Plex"
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
        hosts:
          - host: plex.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"
            secretName: plex-tls

    persistence:
      data:
        enabled: true
        existingClaim: "plex-data-pvc"
      config:
        enabled: true
        type: pvc
        storageClass: longhorn
        size: 20Gi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-1
                - k8s-2
