---
kind: Service
apiVersion: v1
metadata:
  name: nas
  namespace: networking
spec:
  type: ExternalName
  ports:
  - name: https    
    port: 443    
    targetPort: 5001
  externalName: "${NAS_ADDRESS}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas 
  namespace: networking 
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: traefik 
    traefik.frontend.passHostHeader: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    hajimari.io/enable: "true"
    hajimari.io/icon: "nas"
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    external-dns/is-public: "true"
spec:    
  tls:
    - hosts:
        - "nas.${SECRET_DOMAIN}"
      secretName: "nas-tls"
  rules:
    - host: nas.${SECRET_DOMAIN}
      http:
        paths:
        - path: /
          backend:
            serviceName: nas
            servicePort: https