---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nas-tls
  namespace: networking
spec:
  commonName: nas.${SECRET_DOMAIN}
  secretName: nas-tls
  dnsNames:
    - nas.${SECRET_DOMAIN}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: nas
  namespace: networking
spec:
  type: ExternalName
  ports:
    - name: web
      targetPort: 5001
  externalName: 192.168.1.20
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nas
  namespace: networking
  annotations:
    hajimari.io/appName: "nas"
    hajimari.io/enable: "true"
    hajimari.io/icon: "nas"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  entryPoints:
    - "websecure"
  routes:
  - kind: Rule
    match: Host(`nas.${SECRET_DOMAIN}`)
    services:
    - kind: Service
      name: nas
      port: web
  tls:
    nas-tls