---
kind: Service
apiVersion: v1
metadata:
  name: google-external  
  namespace: networking
spec:
  type: ExternalName
  ports:
  - name: https    
    port: 443    
    targetPort: 80
  externalName: google.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: google-ingress 
  namespace: networking 
  annotations:
    kubernetes.io/ingress.class: traefik 
    traefik.frontend.passHostHeader: "false"
    traefik.ingress.kubernetes.io/redirect-regex: ^https://nas.${SECRET_DOMAIN}/(.*)
    traefik.ingress.kubernetes.io/redirect-replacement: https://nas.${SECRET_DOMAIN}/$1
    traefik.ingress.kubernetes.io/redirect-permanent: "false"
spec:    
    rules:
    - host: nas.${SECRET_DOMAIN}
      http:
        paths:
        - path: /
          backend:
            serviceName: google-external
            servicePort: https