---
apiVersion: v1
kind: Service
metadata:
  name: nas
  namespace: networking
spec:
  type: ExternalName
  ports:
    - name: web
      port: 443
      targetPort: 5001
  externalName: 192.168.1.20
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nas
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/appName: "nas"
    hajimari.io/enable: "true"
    hajimari.io/icon: "nas"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  entryPoints:
    - "websecure"
  routes:
  - kind: Rule
    match: Host(`nas.${SECRET_DOMAIN}`)
    services:
    - kind: Service
      name: nas
      port: 5001
      scheme: https
  tls:
    secretName: "nas-tls"
    domains:
      - main: ${SECRET_DOMAIN}
        sans:
          - nas.${SECRET_DOMAIN}