---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bookworm
  namespace: media
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bookworm
            image: craighton/bookworm:2023.4.1-python
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /app/config
              name: config
            - mountPath: /app/secrets
              name: secret
            - mountPath: /app/output
              name: plex
              subPath: Audiobooks
            - mountPath: /app/watch
              name: watch
          restartPolicy: Never
          volumes:
          - name: config
            configMap:
              name: bookworm-config
          - name: secret
            secret:
              secretName: bookworm-secrets
          - name: plex
            persistentVolumeClaim:
              claimName: plex-data-pvc
          - name: watch
            persistentVolumeClaim:
              claimName: bookworm-watch
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                    - amd64