apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: bookworm-secrets
    namespace: media
data:
    activation-bytes: ENC[AES256_GCM,data:OmZUbyY9x/c=,iv:mt55MOL/vbw6aIFTEuqsgzv9WFQfF23i5PVeRUFaFAY=,tag:tHT/LEsRCFEjD89aEQKpOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9nkequ7a7k26n0gvj0j6pm4my9wehxxw8adfwq36yyf267fsffs57shza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSDUybjdMQmRGZ0tKMVdx
            MEFZdE5LVkgvN0VOcWs1NFZYd3lJQkIwSkh3Cm1rTk1rcFF0aTBobHlQLzlhcDhY
            cXoxWkpmdTdBZVZFd2p1cmNTQlZDMVkKLS0tIFFLY3J3cm85ZEZGbXlZWlJtSDUr
            T2xDcG96dndhbExpbXRHUWZuZmtUZm8KW1WlDXF7ZUwoaKU5QqBrJZEhIThp6AOZ
            BQOn85/m5R5jc8dp6HCYNSeFCyuJ0WMWcDvIJJueY8S1tyo8Vezc1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T04:06:45Z"
    mac: ENC[AES256_GCM,data:kP+XNNUi27Swh2ROKCPggw+zhHAgaFH0jwi7PGaMtFgMEJ9LkHfTb8WRh1W1NgyhqPqM8lSIESpbu77XhzjrfJfNo/tFXJZNrtbN/MzK35TBbHVWmFk0XlDhWGaXG7pvt/7L4sbKSDUFX8MB4PDyIycLUNsNmgeyLsXBapIXDdc=,iv:nq4q45dr2/u9bjEHv25AdHeaHBmtqwgncSApntQDwzc=,tag:UR99MAtOyhJKX1+BbCUdhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
