---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookworm-watch
  namespace: media
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume12/bookworm-watch
    server: 192.168.1.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookworm-watch
  namespace: media
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
