---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ema-reader-config
  namespace: home
data:
  config.yml: |-
    ---
    webdriver:
      driver_opts:
        - "--headless"

    auth:
      login_url: "https://www.apsystemsema.com/ema/index.action"
      username_element_id: "username"
      password_element_id: "password"
      login_button_element_id: "Login"
      sign_out_text: "Sign out"
      exception_page: "ema/exceptionIndex.action"

    api:
      timeout: 30
      headers: 
        authority: 'www.apsystemsema.com'
        accept: 'application/json, text/javascript, */*; q=0.01'
        accept-language: 'en-US,en;q=0.9'
        cache-control: 'no-cache'
        content-length: '0'
        origin: 'https://www.apsystemsema.com'
        pragma: 'no-cache'
        referer: 'https://www.apsystemsema.com/ema/security/optmainmenu/intoLargeDashboard.action?language=en_US'
        sec-ch-ua: '"Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"'
        sec-ch-ua-mobile: '?0'
        sec-ch-ua-platform: 'macOS'
        sec-fetch-dest: 'empty'
        sec-fetch-mode: 'cors'
        sec-fetch-site: 'same-origin'
        user-agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'
        x-requested-with: 'XMLHttpRequest'
      endpoints:
        getProductionInfo: 
          uri: "https://www.apsystemsema.com/ema/ajax/getDashboardApiAjax/getDashboardProductionInfoAjax"
        getViewPowerByViewAjax:
          uri: "https://www.apsystemsema.com/ema/ajax/getViewAjax/getViewPowerByViewAjax" 
          date_format: "%Y%m%d"
          body: "sid=2c9f934a81ff8f0501821d822114610b&vid=2c9f934a8247b5f601824c3e246238a4&iid=&date=" # requires adding current date in YYYMMDD format
          delimiter: ","
          response_keys:
            panels: "detail"
            total_power: "power"
            time: "time"

    response_fields:
      power_current: "lastPower"
      energy_today: "today"
      energy_lifetime: "lifetime"
      monitor_status: "meterFlag"
      co2_saved: "co2"

    exception_handling: # these settings will retry over about 1 minute
      max_attempts: 7
      initial_interval: 1
      backoff_multiplier: 2

    mqtt:
      create_home_assistant_sensors: true
      home_assistant:
        panel_sensors:
          prefix: "homeassistant/"
          component: "sensor"
          config_suffix: "config"
          state_suffix: "state"
          device_class: power
          unit_of_measurement: W
          value_template: "{{ value_json.value | int }}"
          name: "Solar Panel"
          unique_id: "solar_panel"
          retain: true
          qos: 0
      client_id: "ema-reader"
      topic_prefix: "homeassistant/energy/solar/"
      topics:
        - name: "power_current"
          qos: 0
          retain: true
        - name: "energy_today"
          qos: 0
          retain: true
        - name: "energy_lifetime"
          qos: 0
          retain: true
        - name: "monitor_status"
          qos: 0
          retain: true
        - name: "co2_saved"
          qos: 0
          retain: true    

    logging:
      level: "debug"
      format: '%(asctime)s - %(levelname)s - [%(name)s] %(message)s'
      redact_sensitive_fields: true