---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ema-reader
  namespace: home
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ema-reader
            image: craighton/ema-reader:2022.8.9
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /ema-reader/config
              name: config
            - mountPath: /ema-reader/secrets
              name: secret
          restartPolicy: Never
          volumes:
          - name: config
            configMap:
              name: ema-reader-config
          - name: secret
            secret:
              secretName: ema-reader-secrets
