apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-config-pv
  namespace: home
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume9/mqtt
    server: ${NAS_ADDRESS}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config-pvc
  namespace: home
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
